[package]
name = "reth-optimism-primitives"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "OP primitive types"

[lints]
workspace = true

[dependencies]
# reth
reth-primitives.workspace = true
reth-primitives-traits.workspace = true
reth-codecs = { workspace = true, optional = true }

# op-reth
reth-optimism-chainspec.workspace = true

# ethereum
alloy-primitives.workspace = true
alloy-consensus.workspace = true
alloy-rlp.workspace = true
alloy-eips.workspace = true

# codecs
modular-bitfield = { workspace = true, optional = true }
zstd = { workspace = true, optional = true }
serde.workspace = true
arbitrary = { workspace = true, features = ["derive"], optional = true }

# misc
derive_more = { workspace = true, features = ["deref"] }
proptest = { workspace = true, optional = true }
rand = { workspace = true, optional = true }

[dev-dependencies]
proptest-arbitrary-interop.workspace = true

[features]
default = ["std", "reth-codec"]
std = ["reth-primitives-traits/std"]
reth-codec = [
    "dep:reth-codecs",
    "dep:zstd",
    "dep:modular-bitfield",
    "std",
    "rand",
    "dep:proptest",
    "dep:arbitrary",
]
arbitrary = [
    "reth-codec",
    "dep:proptest",
    "alloy-eips/arbitrary",
    "rand",
    "reth-primitives-traits/arbitrary",
    "reth-primitives/arbitrary",
]
optimism = [
    "reth-primitives/optimism",
    "reth-codecs/optimism",
]
